### ISSUE TITLE
Work with Taiga 6?

### ISSUE THREAD

**Issue by karezza** [stemid/taiga-contrib-ad-auth#2]
If this works with the latest Taiga then this needs to be updated at the taiga resources page and the local README at github.

**Comment by stemid** [comment]
@karezza Sorry I have abandoned this so I have no idea how it works.

But I'm actually going to setup the latest Taiga soon so maybe I'll have another chance to look at it this summer. I assume there already is a decent AD/LDAP plugin for Taiga now that is better than my plugin. If there isn't then I'll have to revive this code.

**Comment by karezza** [comment]
k
